-- [Basic SELECT]
-- 1. 
SELECT DEPARTMENT_NAME 학과명, CATEGORY 계열
FROM TB_DEPARTMENT;

-- 2. 
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

-- 3. 
SELECT STUDENT_NAME
FROM TB_DEPARTMENT D, TB_STUDENT S
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO AND 
      SUBSTR(S.STUDENT_SSN, 8, 1) = '2' AND 
      S.ABSENCE_YN = 'Y' AND D.DEPARTMENT_NO = 001;
      
-- 4.
SELECT *
FROM TB_STUDENT;
