SELECT ROWID, 
       EMP_ID, 
       EMP_NAME
FROM EMPLOYEE;

SELECT ROWID,
       DEPT_ID
FROM DEPARTMENT;

SELECT *
FROM EMPLOYEE
WHERE EMP_ID = 202;

/*
    <INDEX>
        INDEX는 오라클에서 제공하는 객체로 SQL 명령문의 처리 속도를 향상시키기 위해서 행들의 위치 정보를 가지고 있다
*/

-- 춘대학교 계정 이동
SELECT *
FROM TB_STUDENT
WHERE STUDENT_NAME = '황효종';
--WHERE STUDENT_NO = 'A511332';

-- 비고유 인덱스 생성
CREATE /* UNIQUE */ INDEX IDX_STUDENT_NAME
ON TB_STUDENT(STUDENT_NAME);

-- 결합 인덱스 생성
--A617031	C2272800
SELECT *
FROM TB_GRADE
WHERE STUDENT_NO = 'A617031' AND CLASS_NO = 'C2272800';

CREATE INDEX IDX_STUDENT_CLASS_NO
ON TB_GRADE(STUDENT_NO, CLASS_NO);

-- INDEX 삭제
DROP INDEX IDX_STUDENT_NAME;
DROP INDEX IDX_STUDENT_CLASS_NO;






