/*
    <SEQUENCE>
        정수값을 자동으로 생성하는 역할을 하는 객체이다
*/
-- EMPLOYEE 테이블의 PK 값을 생성할 시퀀스 생성 
CREATE SEQUENCE SEQ_EMPNO
START WITH 300
INCREMENT BY 5
MAXVALUE 310
NOCYCLE
NOCACHE;

-- 현재 계정이 가지고 있는 시퀀스들에 대한 정보를 조회하는 데이터 딕셔너리
SELECT * FROM USER_SEQUENCES;

-- NEXTVAL를 한 번이라도 수행하지 않는 이상 CURRVAL를 가져올 수 없다
SELECT SEQ_EMPNO.CURRVAL FROM DUAL; -- 에러

SELECT SEQ_EMPNO.NEXTVAL FROM DUAL; -- 300
SELECT SEQ_EMPNO.CURRVAL FROM DUAL; -- 300
SELECT SEQ_EMPNO.NEXTVAL FROM DUAL; -- 305
SELECT SEQ_EMPNO.NEXTVAL FROM DUAL; -- 310
-- 지정한 MAXVALUE 값을 초과햇기 때문에 오류 발생
SELECT SEQ_EMPNO.NEXTVAL FROM DUAL; -- ERROR / LAST NUMBER에는 315라고 기록만 됨


/*
    <SEQUENCE 수정>
*/
ALTER SEQUENCE SEQ_EMPNO
--START WITH 200; -- ERROR 수정 불가
INCREMENT BY 10
MAXVALUE 400;

SELECT * FROM USER_SEQUENCES;

SELECT SEQ_EMPNO.CURRVAL FROM DUAL; -- 310
SELECT SEQ_EMPNO.NEXTVAL FROM DUAL; -- 320

/*
    <SEQUENCE 삭제>
*/
DROP SEQUENCE SEQ_EMPNO;

----------------------------------
-- 메번 새로운 사번이 발생되는 시퀀스 생성
CREATE SEQUENCE SEQ_EMPID
START WITH 300;

SELECT * FROM USER_SEQUENCES;

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_NO)
VALUES(SEQ_EMPID.NEXTVAL, '이정후', '980820-1111111');

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_NO)
VALUES(SEQ_EMPID.NEXTVAL, '김태진', '951007-1111111');

SELECT * FROM EMPLOYEE;

ROLLBACK;